version: '3.8'

services:
  perforce:
    image: perforce/p4d:latest
    container_name: perforce-server
    ports:
      - "1666:1666"
    environment:
      - P4USER=superuser
      - P4PASSWD=yourpassword
    volumes:
      - ./mnt/data/depot:/perforce
      - ./mnt/data/config:/etc/perforce
    restart: unless-stopped
    networks:
      - ci-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./mnt/jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped
    networks:
      - ci-network
  
  unreal-engine:
    build:
      context: ./unreal
      dockerfile: Dockerfile
    container_name: unreal-engine
    volumes:
      - ./project:/project
    working_dir: /project
    networks:
      - ci-network
    depends_on:
      - perforce

networks:
  ci-network:
    driver: bridge
